### ISSUE TITLE
Call to a member function checkAccess() on null in Frontend

### ISSUE THREAD

**Issue by marciocamello** [lajax/yii2-translate-manager#1]
/**
     * Initialising front end translator.
     */
    private function _initTranslation() {
        $module = Yii::$app->getModule('translatemanager');
 
        if ($module->checkAccess() && $this->_checkRoles($module->roles)) {
            Yii::$app->session->set(Module::SESSION_KEY_ENABLE_TRANSLATE, true);
        }
    }

**Comment by marciocamello** [comment]
I'm using advanced application new installation

**Comment by lajax** [comment]
For the translatemanager to work the config settings need to be defined in common/config/main.php (in case of yii2-advanced version). The visibility of the module can be set through user privileges (roles, allowedIPs). Unauthorised access can be prevented this way.

Thanks for the feedback.

**Comment by lajax** [comment]
In order to turn on user privilege checking the authManager has to be enabled in the common config.

**Comment by philippfrenzel** [comment]
got the same issue, can you pls. add it to the docs?

**Comment by lajax** [comment]
Thanks for the suggestion. I added this to the docs.
