### ISSUE TITLE
use Translate Manager module with postgresql.

### ISSUE THREAD

**Issue by emptimd** [lajax/yii2-translate-manager#11]
Hi. I'm using your great module on postgresql db. And it's all good except 2 places where table params are escaping with mysql quotes ( ` ).

### Those are in Language model getGridStatistic action:

```php
 $languages = Language::find()
                    ->select('language_id, COUNT( `lt`.`id` ) AS `status`')
                    ->leftJoin(LanguageTranslate::tableName() . ' AS `lt`', '`language`.`language_id` = `lt`.`language`')
                    ->groupBy('language_id')
                    ->all();
```
### And namespace lajax\translatemanager\services; class Generator 

```php
 private function _getLanguageItems() {
        $this->_languageItems = LanguageSource::find()->joinWith([
                'languageTranslate' => function ($query) {
                        $query->where('language_translate.language = :language', [':language' => $this->_languageId]);
                    }
                ])->where('`category` = :category', [':category' => 'javascript'])->all();
    }
```
For postgresql usage, those quotes can be removed or use some Yii functionality ( I'm noob so i can't make pull request sorry).

Thanks in advance.
Great module.

**Comment by lajax** [comment]
Hi!

Thanks for letting me know.
I'll fix this today.

Best Regards,
Lajax
