### ISSUE TITLE
Wrong cyrillic md5 ( javascript )

### ISSUE THREAD

**Issue by zxczxc12** [lajax/yii2-translate-manager#112]
https://www.dropbox.com/s/9ahoffa58591y6d/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202017-10-09%2014.26.39.png?dl=0

https://www.dropbox.com/s/hw8mnkmi8wm9yy4/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202017-10-09%2014.26.44.png?dl=0

but this javascript is working well

http://pajhome.org.uk/crypt/md5/instructions.html

**Comment by moltam** [comment]
Thanks for your report, and your suggestion!
