### ISSUE TITLE
how to change layout view of the extension

### ISSUE THREAD

**Issue by masihfathi** [lajax/yii2-translate-manager#113]
how can i change the layout of the extension to use my layout when u click on the menu item the layout change.

**Comment by moltam** [comment]
You can configure in the [Module settings](https://github.com/lajax/yii2-translate-manager/blob/e2c51b3da5d3f5235b4e83073b558064f7175067/Module.php#L109)

**Comment by masihfathi** [comment]
thanks for your help and great work in this extension
