### ISSUE TITLE
frontend translation problem

### ISSUE THREAD

**Issue by ehasoo** [lajax/yii2-translate-manager#117]
Hey, can someone show me direction my problem is when i hit toggle translate i get 500 error. tried to google it and didn't find anything close to fix.

request body:
content type : 'application/x-www-form-urlencoded; charset=UTF-8'
raw : 'hash=589ab34e870b80c8c7d035805452df19&category=apptask&language_id=et-EE'

here is error stack:
`yii\base\InvalidArgumentException: Key "MD5(message)" is not a column name and can not be used as a filter in /vagrant/hausing/basic/vendor/yiisoft/yii2/db/ActiveRecord.php:218
Stack trace:
#0 /vagrant/hausing/basic/vendor/yiisoft/yii2/db/ActiveRecord.php(190): yii\db\ActiveRecord::filterCondition(Array)
#1 /vagrant/hausing/basic/vendor/yiisoft/yii2/db/BaseActiveRecord.php(112): yii\db\ActiveRecord::findByCondition(Array)
#2 /vagrant/hausing/basic/vendor/lajax/yii2-translate-manager/controllers/actions/DialogAction.php(27): yii\db\BaseActiveRecord::findOne(Array)
#3 [internal function]: lajax\translatemanager\controllers\actions\DialogAction->run()
#4 /vagrant/hausing/basic/vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array)
#5 /vagrant/hausing/basic/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\Action->runWithParams(Array)
#6 /vagrant/hausing/basic/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('dialog', Array)
#7 /vagrant/hausing/basic/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('translatemanage...', Array)
#8 /vagrant/hausing/basic/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#9 /vagrant/hausing/basic/web/index.php(12): yii\base\Application->run()
#10 {main}`

![image](https://user-images.githubusercontent.com/7228377/38265706-4fdcda1c-377f-11e8-8c2c-58927b4222cb.png)

**Comment by moltam** [comment]
This is probably caused by the changes to `findOne` in 2.0.15. I'll need to look for a solution.
