### ISSUE TITLE
Declaration \services\scanners\ScannerFile::extractMessages() incompatible

### ISSUE THREAD

**Issue by sadgmbh** [lajax/yii2-translate-manager#13]
With latest Yii2 2.0.4-dev this error occurs on scan and optimize page:

PHP Strict Warning – yii\base\ErrorException
Declaration of lajax\translatemanager\services\scanners\ScannerFile::extractMessages() should be compatible with yii\console\controllers\MessageController::extractMessages($fileName, $translator, $ignoreCategories = Array)

To fix it, just alter `lajax\translatemanager\services\scanners\ScannerFile` in line `123`:

old:
`protected function extractMessages($fileName, $options) {`

new:
`protected function extractMessages($fileName, $options, $ignoreCategories = []) {`

**Comment by lajax** [comment]
Hi!

Thanks for letting me know.
 I'll fix this today or this week.

Best Regards,
Lajax
