### ISSUE TITLE
tableName from the Language Model

### ISSUE THREAD

**Issue by Julian-B90** [lajax/yii2-translate-manager#14]
I can´t customise the tableName from this Model =>
https://github.com/lajax/yii2-translate-manager/blob/master/models/Language.php#L58

**Comment by lajax** [comment]
You can customise the name of the table by changing the languageTable public variable.

eg.:

```php
'translatemanager' => [
            'class' => 'lajax\translatemanager\Module',
            'languageTable' => 'YourTableName',
            // ...
    ]
```
Best Regards,
Lajax

**Comment by Julian-B90** [comment]
Thank You. :+1:
