### ISSUE TITLE
 Cannot save translated content

### ISSUE THREAD

**Issue by lenhattung** [lajax/yii2-translate-manager#141]
When I click on the save button, I see an "X" error. No rows are saved to the database.

Please help me to fix the error.
<img width="588" alt="Error" src="https://user-images.githubusercontent.com/49211930/98694540-dd89bc00-2371-11eb-9cf6-5377c99b9c02.png">

**Comment by moltam** [comment]
Could you check the log for the AJAX request in the Yii debug toolbar? There should be an error entry there, that will describe what happened.

**Comment by lenhattung** [comment]
Dear Moltam,

I reconfigure the LanguageController file with the following content:
public function behaviors ()
    {
        return [
            'ghost-access' => [
                'class' => 'webvimark \ modules \ UserManagement \ components \ GhostAccessControl',
            ],
        ];
    }

I have debugged and seen everything OK. Can't see any error from Yii2 debugging tool. (Attached photo).
I still cannot store the translated content into the database.
I am looking forward to your help.

<img width="382" alt="1" src="https://user-images.githubusercontent.com/49211930/98920437-67e83200-24d0-11eb-931a-cd399cff3384.png">
<img width="960" alt="2" src="https://user-images.githubusercontent.com/49211930/98920451-6ae32280-24d0-11eb-9d1f-a220f8b6958e.png">

**Comment by lenhattung** [comment]
Dear sir,

This is my error:
{"id":["ID is invalid."],"language":["Language is invalid."]}

**Comment by lenhattung** [comment]
No matter which button I press on, I always see data like this:
{"id": 0, "language": "en", "translation": ""}

**Comment by lenhattung** [comment]
Thank you very much, I have changed the translate.js content:
  helpers.get ($ ('# language_id'). data ('url'), data);

Now everything is working fine.
