### ISSUE TITLE
Dynamic php variables not working

### ISSUE THREAD

**Issue by roshan2014rishu** [lajax/yii2-translate-manager#142]
I am adding translation and I have to use dynamic category names in the place of static category names. When I scan it doesn't show any new translation added.
`$category = "myApp";
Yii::t($category, 'My Translation message');`

**Comment by gs63875** [comment]
@lajax @moltam facing same issue any solution?

**Comment by moltam** [comment]
In short, this is not supported.

The scanner analyses your code statically, it cannot evaluate dynamic expressions. If your category depends on some condition that is evaluated at runtime, the scanner cannot detect it, as it would need to run your code.
