### ISSUE TITLE
Incomplete database configuration: columns in Backend

### ISSUE THREAD

**Issue by marciocamello** [lajax/yii2-translate-manager#2]
if (is_array($this->_tables)) {
            foreach ($this->_tables as $tables) {
                if (empty($tables['connection'])) {
                    throw new InvalidConfigException('Incomplete database  configuration: connection ');
                } else if (empty($tables['table'])) {
                    throw new InvalidConfigException('Incomplete database  configuration: table ');
                } else if (empty($tables['columns'])) {
                    throw new InvalidConfigException('Incomplete database  configuration: columns ');
                }
            }
        }

**Comment by marciocamello** [comment]
I'm using advanced application new installation

**Comment by lajax** [comment]
Sorry, I mistakenly used 'fields' instead of 'columns' in one of the examples. It has been fixed now.

Thanks for the feedback

**Comment by marciocamello** [comment]
Yeah I see :D, thanks
