### ISSUE TITLE
what i am wrong in installation?

### ISSUE THREAD

**Issue by gomonkey** [lajax/yii2-translate-manager#28]
ReflectionException
Class lajax\translatemanager\Module does not exist

i have some problem with composer, i can not install, so i downloaded the extension from this reposity, imported sql tables and insert the folder in: vendor/lajax/yii2-translatemanager 

Then i followed the steps in $config

the page is: url/translatemanager/language/scan

What i wrong?
thanks

**Comment by lajax** [comment]
Hi!

Without composer you can add a package to your app with the following method:

Advanced App:
index.php
```php
$loader = require(__DIR__ . '/../../vendor/autoload.php');
$loader->addPsr4('lajax\\translatemanager\\', __DIR__ . '/../../vendor/lajax/yii2-translate-manager/');
```

Basic App:
index.php
```php
$loader = require(__DIR__ . '/../vendor/autoload.php');
$loader->addPsr4('lajax\\translatemanager\\', __DIR__ . '/../vendor/lajax/yii2-translate-manager/');
```

Best Regards,
