### ISSUE TITLE
Filter case sensetive in postgresql

### ISSUE THREAD

**Issue by sluchznak** [lajax/yii2-translate-manager#39]
Hello, filter is case sensetive

**Comment by Quexer69** [comment]
Could you please give some more information ? Thanks

**Comment by sluchznak** [comment]
https://monosnap.com/file/s92KseQWTw78YUSrucSBa7vfnWfURY
https://monosnap.com/file/wm4JXnQPY2Dcl2IufQbgzcZ5NK2QzY

**Comment by sluchznak** [comment]
DB is PostgreSQL 9.4.3 on x86_64-apple-darwin14.3.0, compiled by Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn), 64-bit

**Comment by sluchznak** [comment]
Could you set lower or upper case strings before equals

**Comment by sluchznak** [comment]
in postgresql to search in case insensetive mode used command ILIKE

**Comment by Quexer69** [comment]
PR welcome :)
