### ISSUE TITLE
scan in wrong base path

### ISSUE THREAD

**Issue by kupika** [lajax/yii2-translate-manager#42]
it scans one level higher than defined. in configuration is defined as root "@app". 
The path should i.e. /var/www/myapp but i get /var/www.
The Problem is line 204 in the following file: 

/services/scanners/ScannerFile.php

wrong:
return dirname(Yii::getAlias($this->module->root));

correct:
return Yii::getAlias($this->module->root);

**Comment by moltam** [comment]
Known issue, see #12 
> One good workaround in the current version is to set @web as 'root'.

**Comment by kupika** [comment]
Thank you.
