### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by emilianoc-tkf** [lajax/yii2-translate-manager#47]
Hello, how are you? I've implemented the plugin in my application but when the user isn't logged, the messages aren't translated, when the user is logged all works ok. Do you know the reason of this problem? Maybe the plugin has some configuration that block translations when the user isn't logged.

I would appreciate if you can help me with this issue! :)

**Comment by lajax** [comment]
The extension does not differentiate between logged in and visitor state during translation.

Best Regards
