### ISSUE TITLE
translate/scan

### ISSUE THREAD

**Issue by Lawiet** [lajax/yii2-translate-manager#48]
Good day,

I try ./yii translate/scan

and 

Scanning translations...
PHP Notice 'yii\base\ErrorException' with message 'Trying to get property of non-object'

in /var/www/html/yii/vendor/lajax/yii2-translate-manager/services/Scanner.php:68

Stack trace:
#0 /var/www/html/yii/vendor/lajax/yii2-translate-manager/services/Scanner.php(68): yii\base\ErrorHandler->handleError(8, 'Trying to get p...', '/var/www/html/g...', 68, Array)
#1 /var/www/html/yii/vendor/lajax/yii2-translate-manager/commands/TranslatemanagerController.php(37): lajax\translatemanager\services\Scanner->run()
#2 [internal function]: lajax\translatemanager\commands\TranslatemanagerController->actionScan()
#3 /var/www/html/yii/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#4 /var/www/html/yii/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\InlineAction->runWithParams(Array)
#5 /var/www/html/yii/vendor/yiisoft/yii2/console/Controller.php(91): yii\base\Controller->runAction('scan', Array)
#6 /var/www/html/yii/vendor/yiisoft/yii2/base/Module.php(455): yii\console\Controller->runAction('scan', Array)
#7 /var/www/html/yii/vendor/yiisoft/yii2/console/Application.php(167): yii\base\Module->runAction('translate/scan', Array)
#8 /var/www/html/yii/vendor/yiisoft/yii2/console/Application.php(143): yii\console\Application->runAction('translate/scan', Array)
#9 /var/www/html/yii/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#10 /var/www/html/yii/yii(19): yii\base\Application->run()
#11 {main}

**Comment by moltam** [comment]
Is your Translate Manager module configured properly in the console app?
You should configure the module in the common config, so the scanner can use it.

**Comment by Lawiet** [comment]
this my web.php

$config = [
    'id' => 'basic',
    'basePath' => dirname(__DIR__),
    'bootstrap' => ['log','translatemanager','gii','debug'],
    'layout' => 'main',
    'language' => 'es',
    'sourceLanguage' => 'es',
    'controllerMap' => [
        'translate' => \lajax\translatemanager\commands\TranslatemanagerController::className(),
    ],

**Comment by moltam** [comment]
The module declaration is missing. Add this to your config in web.php:

```php
'modules' => [
    'translatemanager' => [
        'class' => 'lajax\translatemanager\Module',
    ],
],
```

**Comment by moltam** [comment]
Sorry, I mean `config/console.php` config file (if you are using basic app).

**Comment by moltam** [comment]
Also you should have the same configuration for web and console. I am not very familiar with the basic app, but I think you should create a separate module config for the extension, then require in each config file.

Create console/translatemanager.php:
```php
return [
    'class' => 'lajax\translatemanager\Module',
    // additional config ...
];
```

In the web.php and console.php:
```php
'modules' => [
    'translatemanager' => require(__DIR__ . '/translatemanager.php'),
],

**Comment by Lawiet** [comment]
Ok, very thanks.

console.php 


return [
    'id' => 'basic-console',
    'basePath' => dirname(__DIR__),
    'bootstrap' => ['log', 'gii'],
    'controllerNamespace' => 'app\commands',
    'modules' => [
        'gii' => 'yii\gii\Module',
        'translatemanager' => [
            'class' => 'lajax\translatemanager\Module',
        ],
    ],
    'controllerMap' => [
        'translate' => \lajax\translatemanager\commands\TranslatemanagerController::className(),
    ],


and web.php

$config = [
    'id' => 'basic',
    'basePath' => dirname(__DIR__),
    'bootstrap' => ['log','translatemanager','gii','debug'],
    'layout' => 'main',
    'language' => 'es',
    'sourceLanguage' => 'es',
    'controllerMap' => [
        'translate' => \lajax\translatemanager\commands\TranslatemanagerController::className(),
    ],

.... 

    'modules' => [
        /* ********************** SOLO PARA EDICION SEGUN LA IP ********************** */
        'debug' => [
            'class' => 'yii\debug\Module',
            'allowedIPs' => $allowedIPs,
        ],
        'gii' => [
            'class' => 'yii\gii\Module',
            'allowedIPs' => $allowedIPs,
        ],
        'translatemanager' => [
            'class' => 'lajax\translatemanager\Module',
            'root' => '@app',               // The root directory of the project scan.
            'layout' => 'language',
