### ISSUE TITLE
Cannot run yii translate/scan

### ISSUE THREAD

**Issue by zakdma** [lajax/yii2-translate-manager#49]
I'm using Yii Advanced Template
I have configured translationmanager module in common/config/main.php and its visual interface works for backend like http://dev.yiia.com/backend/translatemanager/language/list
And frontend:
http://dev.yiia.com/frontend/translatemanager/language/list

1) How can I scan both parts backend and frontend simultaneously? Now using visual interface I can do it separately for backend and frontend.
2) I cannot run console command yii.bat translate/scan
It returns Error: Unknown command "translate/scan"

**Comment by moltam** [comment]
2) Did you configure the [controllerMap](https://github.com/lajax/yii2-translate-manager#console-commands)?

**Comment by moltam** [comment]
1) With de default root (`@app`) it scans the entire project root (the scanner moves up one directory from the specified root). Try it this way, if you modified your config.

**Comment by zakdma** [comment]
moltam, thank you, all works well now!
