### ISSUE TITLE
Scanners have an issue due to eval usage

### ISSUE THREAD

**Issue by philippfrenzel** [lajax/yii2-translate-manager#5]
exception 'yii\base\ErrorException' with message 'syntax error, unexpected ')'' in /Users/philippfrenzel/Sites/ph-neighbordrop/vendor/lajax/yii2-translate-manager/services/scanners/ScannerFile.php(121) : eval()'d code:1
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main}

**Comment by lajax** [comment]
I am looking for the cause of the issue but unfortunately I myself haven't been able to reproduce it so far. Can you send over the definition of the language element that causes the issue?

**Comment by philippfrenzel** [comment]
sadly no... looks like some issue with code formatts

**Comment by philippfrenzel** [comment]
Hi again, it Looks like it has the issue with the Plural and or Singular Syntax Using the Wave brakets:( {} look neighbordrop com and if you register you can go to the backend and run the scanners...

**Comment by lajax** [comment]
Thanks for the help, the issue is now clear. It will take a couple of days to fix it. Perhaps I can finish it by next week.

**Comment by philippfrenzel** [comment]
Cool! Thank you! Great Extension! I want to use it Further !
