### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by germanigortcev** [lajax/yii2-translate-manager#70]
The translation module is needed only in the administrative part.

Button to switch the translation on the frontend does not work. The button appears, but no action happens when clicked.

Why should I link a module to the frontend to be translated via a button?

Ext. don't work on advansed template.

 PHP Fatal Error – yii\base\ErrorException
Call to a member function checkAccess() on a non-object

https://s.mail.ru/5QXg/1naGZ22Zi

Auth manager is configured on common/config/main.conf 

Toogle Translate doesn't work/

Configuration

common/config/main.php

http://pastebin.com/gUXXLMEB

frontend/config/main.php

http://pastebin.com/YMfR812c

backend/config/main.php
http://pastebin.com/whyGizrc

And controllers with init()

**Comment by moltam** [comment]
`$module` must be null, according to the error message. If I see right, your module configured in backend. You need to configure on common, if you wish to use on multiple app tiers.

**Comment by germanigortcev** [comment]
Ok/ I moved module in to common\config\main.php

Why Toogle Button doesn't work? Assets was register.

**Comment by moltam** [comment]
Maybe #66 will help.

**Comment by germanigortcev** [comment]
It is help but lables is not encoded and display with style tag

**Comment by moltam** [comment]
What do you mean exactly? Can you show an example?

Maybe #45 is relevant.
