### ISSUE TITLE
Optimaze 

### ISSUE THREAD

**Issue by germanigortcev** [lajax/yii2-translate-manager#74]
I am doing the translation attributes in the model through behavior. After the transfer, they entered into a database for translation. But when you start optimization removes them. Although their transfer is required.

How to exclude the removal by optimization?

` public function behaviors()
    {
        return [
            [
                'class' => TranslateBehavior::className(),
                'translateAttributes' => ['name', 'description'],
            ],
        ];
    }`

**Comment by moltam** [comment]
You should configure your tables in the module configuration (see readme).

**Comment by germanigortcev** [comment]
Do you meen...

`        'tables' => [                   // Properties of individual tables
            [
                'connection' => 'db',   // connection identifier
                'table' => '{{%language}}',         // table name
                'columns' => ['name', 'name_ascii'],// names of multilingual fields
                'category' => 'database-table-name',// the category is the database table name
            ]
        ]`

**Comment by moltam** [comment]
Yes

**Comment by germanigortcev** [comment]
Thanks. Have a good day
