### ISSUE TITLE
Optimize and Scan error only remotely

### ISSUE THREAD

**Issue by infoitservit** [lajax/yii2-translate-manager#75]
In my local server these two functions works with no problems.
Remotely, on the stage server (digital ocean virtual machine, backend on virtualhost with port 8081) i've this error:

![schermata del 2016-04-07 17 41 02](https://cloud.githubusercontent.com/assets/3064689/14357235/35123ff2-fce8-11e5-9871-4c85608bba3b.png)

**Comment by moltam** [comment]
Do you have PHP 7 on your staging server? 

This was fixed in the latest (1.5.3) version by merging #58 , you should update your extension.

**Comment by infoitservit** [comment]
Oh, thank you so much...
