### ISSUE TITLE
root can't be set as array

### ISSUE THREAD

**Issue by blendsoft** [lajax/yii2-translate-manager#79]
'translatemanager' => [
            'class' => 'lajax\translatemanager\Module',
            'root' => [
                '@app/themes/seewroclaw',
                '@app/modules',
            ],
        ],

causes

PHP Warning – yii\base\ErrorException

strncmp() expects parameter 1 to be string, array given

in /vendor/yiisoft/yii2/BaseYii.php

**Comment by moltam** [comment]
Array root handling is not yet released, it is available in dev-master.

**Comment by squio** [comment]
@moltam when do you expect to release the multi root version? It is confusing that this option is documented already while not yet available in the release.

**Comment by moltam** [comment]
This is now resolved, the release was tagged.
