### ISSUE TITLE
Maximum execution  alternative for translatemanager/language/scan

### ISSUE THREAD

**Issue by obladon25** [lajax/yii2-translate-manager#84]
Hello.
At my website is located on an external server.
And I have an error:
"Fatal Error PHP - Yii \ base \ ErrorException
Maximum execution time of 15 seconds Exceeded
"

and the server does not offer the possibility to exchange property "max_execution_time".

How to make expressions <? = Yii :: t ('cat', 'Test_to_Translate);?> To register in the database to be translated without running the scanning action
(/translatemanager/language/scan).

It would be ideal if when I access a particular page to check if there are expressions when translating them to register DB.
I have a bad English.
Thank you.

**Comment by moltam** [comment]
Scan on localhost, export into a file (url: `translatemanager/language/export`), then import on the server (url: `translatemanager/language/import`)

**Comment by obladon25** [comment]
Thank you. it is a good idea ;)
