### ISSUE TITLE
'all languages bundle' seems to break seperate file usages

### ISSUE THREAD

**Issue by rhertogh** [lajax/yii2-translate-manager#92]
Pull request #81(added bundle that supports all active languages) seems to break the translations when using single files. The latest language that is saved is being used for all language files and the translation is not correctly replaced on the front-end.

**Comment by moltam** [comment]
I discovered that this is still an issue, even without using the bundle. 

PR #81 changed the format of JS files, so the old messages won't be loaded correctly after updating to a newer version that contains this PR. The regeneration of files solves the issue, but there is no function for that. 

So the PR is BC breaking, and should be removed for now (maybe it could be reimplemented later after solving these issues).
