### ISSUE TITLE
Google translation

### ISSUE THREAD

**Issue by MixMe** [lajax/yii2-translate-manager#97]
is not working ;)

**Comment by mishfish** [comment]
Have you generate and add your google Api Key to config?

**Comment by moltam** [comment]
It is working for me too.

**Comment by MixMe** [comment]
Google Translation was removed ?
![capture](https://user-images.githubusercontent.com/3535911/47416376-3fbcf780-d77e-11e8-985f-cfe1bd4105fe.PNG)

**Comment by MixMe** [comment]
or how i can use it ?

**Comment by moltam** [comment]
Yes, it was removed. It never made into a tagged release. Currently you can't use this feature. For details, see the [conversation](https://github.com/lajax/yii2-translate-manager/commit/7e3245b37b537656ef2669d1099c71b4f640d838#commitcomment-27452834) at the commit.
